version: 2
updates:
  - package-ecosystem: "gomod" # Specify the package manager
    directory: "/" # Root directory or specific path
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    target-branch: "develop"
    groups:
      action-plugins:
        patterns:
          - "/action-plugins/*/"
      endpoint-plugins:
        patterns:
          - "/endpoint-plugins/*/"