name: Check action-plugins Build - step_analysis

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ "develop" ]
    paths:
      - "action-plugins/step_analysis/**"

jobs:
  build-plugin:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'

      - name: Build Plugin
        working-directory: action-plugins/step_analysis
        run: go build
